spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    embedded:
      enabled: false


server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics
logging:
  level:
    org.abondar.exerimental: INFO