spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    embedded:
      enabled: false


server:
  port: 8085

camel:
  lra:
    coordinator-url: http://localhost:8080/lra-coordinator  # Assuming the LRA Coordinator runs on port 8080
    participant-auto-join: true
    timeout: 300000

logging:
  level:
    org.abondar.exerimental: INFO