spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    embedded:
      enabled: false

camel:
  lra:
    local-participant-url: http://localhost:8080/lra-coordinator
    coordinator-url: http://localhost:8080/lra-coordinator
    coordinator-context-path: lra-coordinator
    enabled: true