spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    embedded:
      enabled: false

server:
  port: 8020

camel:
  component:
    servlet:
      allow-java-serialized-object: true
      enabled: true
