spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    embedded:
      enabled: false

server:
  port: 8020

camel:
  servlet:
    mapping:
      context-path: /api/*
  component:
    servlet:
      allow-java-serialized-object: true
      enabled: true


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics,mappings